name: ASP.NET Backend CI

on:
  push:
    branches:
      - Backend
  pull_request:
    branches:
      - Backend

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: dotnet restore ./Vizsga_Backend/Vizsga_Backend.sln  # Itt adjuk meg az elérési utat

      - name: Build the project
        run: dotnet build ./Vizsga_Backend/Vizsga_Backend.sln --configuration Release  # Itt is meg kell adni az elérési utat

      - name: Run tests
        run: dotnet test ./Vizsga_Backend/Vizsga_Backend.sln --configuration Release --verbosity normal  # Itt is az elérési utat kell használni
