name: Run Tests

on:
  push:
    branches: [ "Backend" ]
  pull_request:
    branches: [ "Backend" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Vizsga_Backend/Vizsga_Backend.sln

    - name: Build solution
      run: dotnet build ./Vizsga_Backend/Vizsga_Backend.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./Vizsga_Backend/Vizsga_Backend.sln --configuration Release --no-build --verbosity normal
