name: ASP.NET Backend CI

on:
  push:
    branches:
      - Backend
  pull_request:
    branches:
      - Backend

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      # 1. Check out repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # 2. Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      # 3. Restore dependencies (ensure all dependencies are restored)
      - name: Restore dependencies
        run: dotnet restore ./Vizsga_Backend/Vizsga_Backend.sln

      # 4. Run tests (now ensuring the tests are properly executed)
      - name: Run tests
        run: |
          dotnet test ./Vizsga_Backend/Vizsga_Backend.sln --configuration Release --no-build --verbosity normal
